# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  #config.vm.synced_folder "../scripts", "/scripts"
  config.vm.synced_folder "./scripts", "/scripts"
  # config.vm.provision "shell", inline:  "/vagrant/scripts/defaultScript.sh"
  config.vm.provision "shell", inline:  "/scripts/defaultScript.sh"

  # config.vm.box = "generic/ubuntu2204"

  ### iacserver VM ###
  config.vm.define "iacserver", primary: true do |iacserver|
    iacserver.vm.box = "generic/ubuntu2204"
    # iacserver.vm.box = "geerlingguy/centos7"
    iacserver.vm.hostname = "iacserver"
    iacserver.vm.network "private_network", ip: "192.168.75.11"
    # iacserver.vm.boot_timeout = 1800
    iacserver.vm.provider "virtualbox" do |vb|
      vb.name = "iacserver"
      vb.memory = "4096"
    end
    iacserver.vm.provision "shell", inline: "/scripts/deploy_terraform.sh"
  end

end
