ENV["LC_ALL"] = "en_US.UTF-8"
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  #config.vm.synced_folder "../scripts", "/scripts"
  config.vm.provision "shell", inline:  "/vagrant/scripts/defaultScript.sh"
  # config.vm.provision "shell", inline:  <<-SHELL
    # whoami
  #   uname -a
  #   hostname
  #   apt-get update -y
  # SHELL

  ### puppetmaster01 VM ###
  config.vm.define "puppetmaster01", primary: true do |puppetmaster01|
    puppetmaster01.vm.box = "generic/ubuntu2204"
    puppetmaster01.vm.box_version = "4.2.16"
    puppetmaster01.vm.hostname = "puppetmaster01.example.com"
    puppetmaster01.vm.network "private_network", ip: "192.168.75.21"
    #puppetmaster01.vm.synced_folder "../scripts", "/scripts", type="rsync"
    # puppetmaster01.vm.synced_folder "./scripts", "/scripts" #, type="rsync"
    puppetmaster01.vm.synced_folder ".", "/vagrant", disabled: false, owner: "vagrant", group: "vagrant" #, type="rsync"
    puppetmaster01.vm.provider "virtualbox" do |vb|
      vb.name = "puppetmaster01"
      vb.cpus = 2
      vb.memory = "4096"
    end
    # puppetmaster01.vm.provision "shell", inline: "/vagrant/scripts/installPuppetMaster.sh"
  end

  # ### puppetagent01 VM ###
  # config.vm.define "puppetagent01" do |puppetagent01|
  #   puppetagent01.vm.box = "generic/ubuntu2204"
  #   puppetagent01.vm.box_version = "4.2.16"
  #   puppetagent01.vm.hostname = "puppetagent01.example.com"
  #   puppetagent01.vm.network "private_network", ip: "192.168.75.22"
  #   #puppetagent01.vm.synced_folder "../scripts", "/scripts"
  #   puppetagent01.vm.provider "virtualbox" do |vb|
  #     vb.name = "puppetagent01"
  #     vb.memory = "512"
  #   end
  #   # puppetagent01.vm.provision "shell", inline: "/vagrant/scripts/installPuppetAgent01.sh"
  # end

  ### puppetagent02 VM ###
  # config.vm.define "puppetagent02" do |puppetagent02|
  #   puppetagent02.vm.box = "generic/ubuntu2204"
  #   puppetagent02.vm.box_version = "4.2.16"
  #   puppetagent02.vm.hostname = "puppetagent02.example.com"
  #   puppetagent02.vm.network "private_network", ip: "192.168.75.23"
  #   #puppetagent02.vm.synced_folder "../scripts", "/scripts"
  #   puppetagent02.vm.provider "virtualbox" do |vb|
  #     vb.name = "puppetagent02"
  #     vb.memory = "512"
  #   end
  #   # puppetagent02.vm.provision "shell", inline: "/vagrant/scripts/installPuppetAgent02.sh"
  # end

  # (1..3).each do |i|
  #   config.vm.define "puppetagent-#{i}" do |node|
  #     node.vm.provision "shell",
  #       inline: "echo hello from node #{i}"
  #   end
  # end

end
