ENV["LC_ALL"] = "en_US.UTF-8"
Vagrant.configure("2") do |config|

  # config.vm.provider "vmware_desktop" do |vmware|
  #   vmware.allowlist_verified = true
  # end

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  #config.vm.synced_folder "../scripts", "/scripts"
  config.vm.provision "shell", inline:  "/vagrant/scripts/defaultScript.sh"

  ### grafana VM ###
  config.vm.define "grafana", primary: true do |grafana|

    # grafana.vm.provider "vmware_desktop" do |vmware|
    #   vmware.allowlist_verified = true
    # end

    grafana.vm.box = "gyptazy/ubuntu22.04-arm64"
    grafana.vm.hostname = "grafana.example.com"
    grafana.vm.network "private_network", ip: "192.168.75.120"
    grafana.vm.boot_timeout = 1800
    #grafana.vm.synced_folder "../scripts", "/scripts", type="rsync"
    grafana.vm.provider "vmware_desktop" do |vb|
      # vb.name = "grafana"
      vb.vmx["ethernet0.pcislotnumber"] = "160"
      vb.allowlist_verified = true
      vb.cpus = 2
      vb.memory = "2048"
    end
    grafana.vm.provision "shell", inline: "/vagrant/scripts/installGrafana.sh"
    # grafana.vm.provision "shell", inline: <<-SHELL
    #   # apt repolist
    #   apt install -y epel-release
    #   apt repolist

    #   apt install -y wget vim
    #   #  python3-pip
    #   apt install -y ansible

    #   timedatectl set-timezone Africa/Douala
    #   echo "TZ='Africa/Douala'; export TZ" >> ~/.profile
    #   cat /vagrant/scripts/vimrc >> ~/.vimrc
    # SHELL
  end

#   ### lokipromtail VM ###
#   config.vm.define "lokipromtail" do |lokipromtail|

#     lokipromtail.vm.box = "gyptazy/ubuntu22.04-arm64"
#     lokipromtail.vm.hostname = "lokipromtail.example.com"
#     lokipromtail.vm.network "private_network", ip: "192.168.75.121"
#     #lokipromtail.vm.synced_folder "../scripts", "/scripts"
#     lokipromtail.vm.provider "vmware_desktop" do |vb|
#       # vb.name = "lokipromtail"
#       vb.vmx["ethernet0.pcislotnumber"] = "160"
#       vb.allowlist_verified = true
#       vb.memory = "1024"
#     end
#     lokipromtail.vm.provision "shell", inline: "/vagrant/scripts/installDocker.sh"
#   end

  ### web02 VM ###
#   config.vm.define "web02" do |web02|

#     web02.vm.box = "gyptazy/ubuntu22.04-arm64"
#     web02.vm.hostname = "web02.example.com"
#     web02.vm.network "private_network", ip: "192.168.75.112"
#     #web02.vm.synced_folder "../scripts", "/scripts"
#     web02.vm.provider "vmware_desktop" do |vb|
#       # vb.name = "web02"
#       vb.vmx["ethernet0.pcislotnumber"] = "160"
#       vb.allowlist_verified = true
#       vb.memory = "1024"
#     end
#     web02.vm.provision "shell", inline: "/vagrant/scripts/installAnsiTarget.sh"
#   end

  ### db01 VM ###
#   config.vm.define "db01" do |db01|

#     db01.vm.box = "gyptazy/ubuntu22.04-arm64"
#     db01.vm.hostname = "db01.example.com"
#     db01.vm.network "private_network", ip: "192.168.75.113"
#     #db01.vm.synced_folder "../scripts", "/scripts"
#     db01.vm.provider "vmware_desktop" do |vb|
#       # vb.name = "db01"
#       vb.vmx["ethernet0.pcislotnumber"] = "160"
#       vb.allowlist_verified = true
#       vb.memory = "1024"
#     end
#     db01.vm.provision "shell", inline: "/vagrant/scripts/installAnsiTarget.sh"
#   end

  ### db02 VM ###
#   config.vm.define "db02" do |db02|

#     db02.vm.box = "gyptazy/ubuntu22.04-arm64"
#     db02.vm.hostname = "db02.example.com"
#     db02.vm.network "private_network", ip: "192.168.75.114"
#     #db02.vm.synced_folder "../scripts", "/scripts"
#     db02.vm.provider "vmware_desktop" do |vb|
#       # vb.name = "db02"
#       vb.vmx["ethernet0.pcislotnumber"] = "160"
#       vb.allowlist_verified = true
#       vb.memory = "1024"
#     end
#     db02.vm.provision "shell", inline: "/vagrant/scripts/installAnsiTarget.sh"
#   end

  # (1..3).each do |i|
  #   config.vm.define "puppetagent-#{i}" do |node|
  #     node.vm.provision "shell",
  #       inline: "echo hello from node #{i}"
  #   end
  # end

end
