ENV["LC_ALL"] = "en_US.UTF-8"
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  #config.vm.synced_folder "../scripts", "/scripts"
  # config.vm.provision "shell", inline:  "/vagrant/scripts/defaultScript.sh"

  ### kalilinux VM ###
  config.vm.define "kalilinux", primary: true do |kalilinux|
    kalilinux.vm.box = "kalilinux/rolling"
    kalilinux.vm.box_version = "2023.2.0"
    kalilinux.vm.hostname = "kalilinux.example.com"
    kalilinux.vm.network "private_network", ip: "192.168.75.101"
    #kalilinux.vm.synced_folder "../scripts", "/scripts", type="rsync"
    kalilinux.vm.provider "virtualbox" do |vb|
      vb.name = "kalilinux"
      vb.cpus = 2
      vb.memory = "4096"
    end
    # kalilinux.vm.provision "shell", inline: "/vagrant/scripts/installPuppetMaster.sh"
    kalilinux.vm.provision "shell", inline: "/vagrant/scripts/defaultScript.sh"
  end

  ### metasploitable VM ###
  config.vm.define "metasploitable" do |metasploitable|
    metasploitable.vm.box = "rapid7/metasploitable3-win2k8"
    metasploitable.vm.box_version = "0.1.0-weekly"
    metasploitable.vm.hostname = "metasploitable.example.com"
    metasploitable.vm.network "private_network", ip: "192.168.75.102"
    #metasploitable.vm.synced_folder "../scripts", "/scripts"
    metasploitable.vm.provider "virtualbox" do |vb|
      vb.name = "metasploitable"
      vb.memory = "512"
    end
    # metasploitable.vm.provision "shell", inline: "/vagrant/scripts/installmetasploitable.sh"
  end

  # (1..3).each do |i|
  #   config.vm.define "puppetagent-#{i}" do |node|
  #     node.vm.provision "shell",
  #       inline: "echo hello from node #{i}"
  #   end
  # end

end

