Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    #config.vm.synced_folder "../scripts", "/scripts"
    config.vm.synced_folder "./scripts", "/scripts"
    # config.vm.provision "shell", inline:  "/vagrant/scripts/defaultScript.sh"
    config.vm.provision "shell", inline:  "/scripts/defaultScript.sh"

    ### gitlab01 VM ###
    config.vm.define "gitlab01" do |gitlab01|
      # gitlab01.vm.box = "geerlingguy/centos7"
      gitlab01.vm.box = "generic/ubuntu2204"
      gitlab01.vm.hostname = "gitlab01"
      gitlab01.vm.network "private_network", ip: "192.168.75.15"
      # gitlab01.vm.boot_timeout = 1800
      gitlab01.vm.provider "virtualbox" do |vb|
        vb.name = "gitlab01"
        vb.memory = "2048"
      end
      gitlab01.vm.provision "shell", inline: "/scripts/deploy_gitlab.sh"
    end

    ### jenkins01 VM ###
    config.vm.define "jenkins01" do |jenkins01|
      jenkins01.vm.box = "generic/ubuntu2204"
      # jenkins01.vm.box = "geerlingguy/centos7"
      jenkins01.vm.hostname = "jenkins01"
      jenkins01.vm.network "private_network", ip: "192.168.75.11"
      # jenkins01.vm.boot_timeout = 1800
      jenkins01.vm.provider "virtualbox" do |vb|
        vb.name = "jenkins01"
        vb.memory = "2048"
      end
      jenkins01.vm.provision "shell", inline: "/scripts/deploy_jenkins.sh"
    end

    ### APP01 VM ###
    config.vm.define "app01", primary: true do |app01|
      # app01.vm.box = "geerlingguy/centos7"
      app01.vm.box = "generic/ubuntu2204"
      app01.vm.hostname = "app01"
      app01.vm.network "private_network", ip: "192.168.75.12"
      app01.vm.synced_folder "./scripts", "/scripts"
      # app01.vm.boot_timeout = 1800
      app01.vm.provider "virtualbox" do |vb|
        vb.name = "app01"
        vb.memory = "1024"
      end
      app01.vm.provision "shell", inline: "/scripts/deploy_app.sh"
    end

    # ### RMQ01 VM ###
    # config.vm.define "rmq01" do |rmq01|
    #   rmq01.vm.box = "geerlingguy/centos7"
    #   rmq01.vm.hostname = "rmq01"
    #   rmq01.vm.network "private_network", ip: "192.168.75.16"
    #   # rmq01.vm.boot_timeout = 1800
    #   rmq01.vm.provider "virtualbox" do |vb|
    #     vb.name = "rmq01"
    #     vb.memory = "512"
    #   end
    #   # rmq01.vm.provision "shell", inline: "/vagrant/scripts/installAnsibleTarget02.sh"
    # end

    # ### MC01 VM ###
    # config.vm.define "mc01" do |mc01|
    #   mc01.vm.box = "geerlingguy/centos7"
    #   mc01.vm.hostname = "mc01"
    #   mc01.vm.network "private_network", ip: "192.168.75.14"
    #   # mc01.vm.boot_timeout = 1800
    #   mc01.vm.provider "virtualbox" do |vb|
    #     vb.name = "mc01"
    #     vb.memory = "512"
    #   end
    #   # mc01.vm.provision "shell", inline: "/vagrant/scripts/installAnsibleTarget02.sh"
    # end

  end
