ENV["LC_ALL"] = "en_US.UTF-8"
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  #config.vm.synced_folder "../scripts", "/scripts"
  config.vm.provision "shell", inline: "echo Hello"

  ### puppetmaster01 VM ###
  config.vm.define "puppetmaster01" do |puppetmaster01|
    puppetmaster01.vm.box = "centos/7"
    puppetmaster01.vm.hostname = "puppetmaster01"
    puppetmaster01.vm.network "private_network", ip: "192.168.75.11"
    #puppetmaster01.vm.synced_folder "../scripts", "/scripts", type="rsync"
    puppetmaster01.vm.provider "virtualbox" do |vb|
      vb.name = "puppetmaster01"
      vb.cpus = 2
      vb.memory = "2048"
    end
    puppetmaster01.vm.provision "shell",
      inline: "echo hello from Puppet Master"
  end

  ### puppetagent01 VM ###
  config.vm.define "puppetagent01" do |puppetagent01|
    puppetagent01.vm.box = "centos/7"
    puppetagent01.vm.hostname = "puppetagent01"
    puppetagent01.vm.network "private_network", ip: "192.168.75.12"
    #puppetagent01.vm.synced_folder "../scripts", "/scripts"
    puppetagent01.vm.provider "virtualbox" do |vb|
      vb.name = "puppetagent01"
      vb.memory = "512"
    end
  end

  ### puppetagent02 VM ###
  config.vm.define "puppetagent02" do |puppetagent02|
    puppetagent02.vm.box = "centos/7"
    puppetagent02.vm.hostname = "puppetagent02"
    puppetagent02.vm.network "private_network", ip: "192.168.75.13"
    #puppetagent02.vm.synced_folder "../scripts", "/scripts"
    puppetagent02.vm.provider "virtualbox" do |vb|
      vb.name = "puppetagent02"
      vb.memory = "512"
      # vb.memory = "1024"
    end
  end

  # (1..3).each do |i|
  #   config.vm.define "puppetagent-#{i}" do |node|
  #     node.vm.provision "shell",
  #       inline: "echo hello from node #{i}"
  #   end
  # end

end
