ENV["LC_ALL"] = "en_US.UTF-8"
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  #config.vm.synced_folder "../scripts", "/scripts"
  # config.vm.provision "shell", inline:  "/vagrant/scripts/defaultScript.sh"

  ### kkserver01 VM ###
  config.vm.define "kkserver01", primary: true do |kkserver01|
    kkserver01.vm.box = "centos/7"
    kkserver01.vm.hostname = "kkserver01.example.com"
    kkserver01.vm.network "private_network", ip: "192.168.75.123"
    kkserver01.vm.boot_timeout = 1800
    #kkserver01.vm.synced_folder "../scripts", "/scripts", type="rsync"
    kkserver01.vm.provider "virtualbox" do |vb|
      vb.name = "kkserver01"
      vb.cpus = 2
      vb.memory = "4096"
    end
    kkserver01.vm.provision "shell", inline: "/vagrant/scripts/kk_eco_deploy.sh"
    # kkserver01.vm.provision "shell", inline: <<-SHELL
    #   yum repolist
    #   yum install -y epel-release
    #   yum repolist

    #   yum install -y wget vim
    #   #  python3-pip
    #   yum install -y ansible

    #   timedatectl set-timezone Africa/Douala
    #   echo "TZ='Africa/Douala'; export TZ" >> ~/.profile
    #   cat /vagrant/scripts/vimrc >> ~/.vimrc
    # SHELL
  end

end
